# Generated by Django 4.2.1 on 2023-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
