# Generated by Django 4.2.1 on 2023-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0002_city_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.BigIntegerField(),
        ),
    ]
