# Generated by Django 4.2.1 on 2023-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_Players_app', '0003_alter_player_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
